// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3f8W8dQ0j8G2CB43yGaWbcss4hxRkaAo',
    appId: '1:707971165607:web:f9404123db447b6deb9a82',
    messagingSenderId: '707971165607',
    projectId: 'study-sync-esof',
    authDomain: 'study-sync-esof.firebaseapp.com',
    storageBucket: 'study-sync-esof.appspot.com',
    measurementId: 'G-588G668THL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1RWp-j4rTN9mkV4xYcXnLtlyGoT_5oKA',
    appId: '1:707971165607:android:d06cb5b468ae95fdeb9a82',
    messagingSenderId: '707971165607',
    projectId: 'study-sync-esof',
    storageBucket: 'study-sync-esof.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5chZDUYWI6858lqBZuMbfVg1pzEKyQRE',
    appId: '1:707971165607:ios:dad5595e6cdda896eb9a82',
    messagingSenderId: '707971165607',
    projectId: 'study-sync-esof',
    storageBucket: 'study-sync-esof.appspot.com',
    iosBundleId: 'com.example.studySync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5chZDUYWI6858lqBZuMbfVg1pzEKyQRE',
    appId: '1:707971165607:ios:245be1d50331582feb9a82',
    messagingSenderId: '707971165607',
    projectId: 'study-sync-esof',
    storageBucket: 'study-sync-esof.appspot.com',
    iosBundleId: 'com.example.studySync.RunnerTests',
  );
}
